site_name: Craftserve Docs
repo_url: https://github.com/Craftserve/docs/tree/c3
theme:
    name: material
    custom_dir: theme
    logo: common/img/logo.png

extra_css:
    - stylesheets/extra.css

extra_javascript:
  - javascript/redirect.js

extra:
    alternate:
        - name: English
          link: /en-US/
          lang: en
        - name: Polski
          link: /pl-PL/
          lang: pl
    analytics:
        provider: custom

exclude_docs: |
    todo.md

plugins:
    - glightbox
