site_name: Dokumentacja Craftserve
repo_url: https://github.com/Craftserve/docs/tree/c3
theme:
  name: material
  custom_dir: theme
  logo: img/logo.png

extra_css:
  - stylesheets/extra.css

extra:
  analytics:
    provider: custom

exclude_docs: |
  todo.md

plugins:
  - glightbox
