site_name: Dokumentacja Craftserve
repo_url: https://github.com/Craftserve/docs/tree/c3
theme:
  name: material
  custom_dir: theme
  logo: docs/img/logo.png

extra_css:
  - stylesheets/extra.css

extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Polski
      link: /pl-PL/
      lang: pl
  analytics:
    provider: custom

exclude_docs: |
  todo.md

plugins:
  - glightbox
